// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGoODrPn6VRxIA0saXJ4TqtknZat4tUD8',
    appId: '1:18273045377:web:58435caf961b8219473680',
    messagingSenderId: '18273045377',
    projectId: 'companion-d5ae8',
    authDomain: 'companion-d5ae8.firebaseapp.com',
    storageBucket: 'companion-d5ae8.firebasestorage.app',
    measurementId: 'G-EZ7QSY1H02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHlhz_rF-havQzkY4BUjgEMUxjiYNrm_k',
    appId: '1:18273045377:android:9ac79eacc4d40eaa473680',
    messagingSenderId: '18273045377',
    projectId: 'companion-d5ae8',
    storageBucket: 'companion-d5ae8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2H14WnDUs0PdBdovzdeVcAQXz4-X2miY',
    appId: '1:18273045377:ios:94ef386de11cb2a2473680',
    messagingSenderId: '18273045377',
    projectId: 'companion-d5ae8',
    storageBucket: 'companion-d5ae8.firebasestorage.app',
    iosBundleId: 'com.example.companion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2H14WnDUs0PdBdovzdeVcAQXz4-X2miY',
    appId: '1:18273045377:ios:94ef386de11cb2a2473680',
    messagingSenderId: '18273045377',
    projectId: 'companion-d5ae8',
    storageBucket: 'companion-d5ae8.firebasestorage.app',
    iosBundleId: 'com.example.companion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGoODrPn6VRxIA0saXJ4TqtknZat4tUD8',
    appId: '1:18273045377:web:a3147dca78da8ed4473680',
    messagingSenderId: '18273045377',
    projectId: 'companion-d5ae8',
    authDomain: 'companion-d5ae8.firebaseapp.com',
    storageBucket: 'companion-d5ae8.firebasestorage.app',
    measurementId: 'G-BH8XGKM0W4',
  );
}
